# Solutions to Exercise 16: Exact Inference in Bayesian Networks

Given the factorised distribution

$P(C,R,D,A,S,F,T) = P(R)P(C)P(D)P(A\vert C)P(F\vert A)P(T\vert F,D) P(S\vert F,T)$

and the following univariate distributions:


| $P(R)$ | $P(\lnot R)$ |
|:------:|:------------:|
| 0.3    | 0.7          |

<br/>

| $P(C)$ | $P(\lnot C)$ |
|:------:|:------------:|
| 0.1    | 0.9          |

<br/>

| $P(D)$ | $P(\lnot D)$ |
|:------:|:------------:|
| 0.5    | 0.5          |

<br/>

|           | $P(A\vert C)$ | $P(\lnot A\vert C)$ |
|----------:|:-------------:|:-------------------:|
| $C$       | 0.01          |  0.99               |
| $\lnot C$ | 0.0           |  1.00               |

<br/>

|           | $P(F\vert A)$ | $P(\lnot F\vert A)$ |
|----------:|:-------------:|:-------------------:|
| $A$       | 0.30          |  0.70               |
| $\lnot A$ | 0.001         |  0.999              |

<br/>

|                  | $P(T\vert F,D)$ | $P(\lnot T\vert F,D)$ |
|-----------------:|:---------------:|:---------------------:|
| $D,F$            | 0.99            |  0.01                 |
| $D,\lnot F$      | 0.60            |  0.40                 |
| $\lnot D,F$      | 0.70            |  0.30                 |
| $\lnot D,\lnot F$| 0.01            |  0.99                |

<br/>

|                  | $P(S\vert T,F)$ | $P(\lnot S\vert T,F)$ |
|-----------------:|:---------------:|:-------------------:|
| $T,F$            | 0.99            |  0.01                 |
| $T,\lnot F$      | 0.30            |  0.70                 |
| $\lnot T,F$      | 0.99            |  0.01                 |
| $\lnot T,\lnot F$| 0.001           |  0.999                |

Compute the following quantities:


In [2]:
import numpy as np
PR = np.array([0.7,0.3])
PC = np.array([0.9,0.1])
PD = np.array([0.5,0.5])
PA_C = np.array([[1.0, 0.99],[0.0,0.01]])
PA = PA_C @ PC
PF_A = np.array([[0.999, 0.7],[0.001,0.3]])
PT_FD = np.array([[[0.99,0.40],[0.30,0.01]],[[0.01,0.60],[0.70,0.99]]])
PF = PF_A @ PA
PT_F = PT_FD @ PD
PT = PT_F @ PF

1. $P(S)$

$P(S)=\sum_{TF}P(S,T,F)=P(S\vert(T,F)P(T)P(F)$

In [3]:
PS_TF = np.array([[[0.999,0.01],[0.70,0.01]],[[0.001,0.99],[0.30,0.99]]])
# Check
print(PS_TF[1][1][0])

PS_T = PS_TF@PF
print(PS_T)

PS = PS_T @ PT
print(PS)


0.3
[[0.99771529 0.69910369]
 [0.00228471 0.30089631]]
[0.90642929 0.09357071]


2. $P(S,C)$


$P(S,C) = P(S\vert C)P(C) = \sum_{FDA} P(S\vert T,F) P(T\vert F,D) P(F\vert A) P(A\vert C) P(D) P(C)$

This is best handled in stages. We will also use some of the things we have already calculated to reformulate this as:

$P(S,C) = \sum({TFA}P(S\vert T,F) P(T\vert F) T(F) P(A\vert C) P(C)$

where $P(S\vert C) = \sum({TFA}P(S\vert T,F) P(T\vert F) T(F) P(A\vert C)$

In [ ]:
PT_A = PT_F @ PF_A
print(PT_A)

PS_T = PS_TF @ PF
print(PS_T)

PS_A = PS_T @ PT_A
print(PS_A)

PS_C = PS_A @ PA_C
print(PS_C)

PSC = PS_C*PC
print(PSC)


[[0.69446 0.533  ]
 [0.30554 0.467  ]]
[[0.99771529 0.69910369]
 [0.00228471 0.30089631]]
[[0.9064775  0.85826367]
 [0.0935225  0.14173633]]
[[0.9064775  0.90599536]
 [0.0935225  0.09400464]]
[[0.81582975 0.09059954]
 [0.08417025 0.00940046]]


array([0.90642929, 0.09357071])

3. $P(A\vert S)$

For this we will need to use Bayes' rule:

$P(A\vert S) = P(S\vert A)P(A)/P(S)$.

In [5]:
PSA = PS_A * PA
print(PS_A)
print(PA)
print(PSA/PA)

PA_S = PSA.T/PS

print(PA_S)


[[0.9064775  0.85826367]
 [0.0935225  0.14173633]]
[0.999 0.001]
[[0.9064775  0.85826367]
 [0.0935225  0.14173633]]
[[9.99053138e-01 9.98485249e-01]
 [9.46862248e-04 1.51475097e-03]]


4. $P(A\vert T)$

Again, we use Bayes rule: $P(A\vert T) = P(T\vert A)P(A)/P(T)$:

In [6]:
PTA = PT_A * PA
PA_T = PTA.T/PT
print(PA_T)

[[9.99232319e-01 9.98472366e-01]
 [7.67681292e-04 1.52763418e-03]]
