# Importance Sampling

In importance sampling, we generate only those values which we need. This only works on conditioning variables.

In [3]:
import numpy as np

PG = np.array([0.6,0.4])
PM = np.array([0.75,0.25])
PF_M = np.array([[0.8,0.4],[0.2,0.6]])
PP_M = np.array([[0.65,0.45],[0.35,0.55]])

In [ ]:
N = 10000
Trace = np.zeros([N,4])
for i in range(N):
    # Draw one sample from P(G)
    G = np.random.binomial(1,PG[1])
    # Draw one sample from P(M)
    #M = np.random.binomial(1,P_M[1])
    M = 1
    # Draw one sample from P(F|M)
    F = np.random.binomial(1,PF_M[1,M])
    # Draw one sample from P(P|M)
    P = np.random.binomial(1,PP_M[1,M])
    Trace[i:] = np.array([G,M,F,P])


In [5]:
print(f"P_G = {Trace[:,0].sum()/N}")
print(f"P_M = {Trace[:,1].sum()/N}")
print(f"P_F_M = {Trace[:,2].sum()/N}")
print(f"P_P_M = {Trace[:,3].sum()/N}")



P_G = 0.4024
P_M = 1.0
P_F_M = 0.6002
P_P_M = 0.548


# Likelihood Reweighting

First look at conditioning on M

In [6]:
N = 10000
Trace = np.zeros([N,5])
for i in range(N):
    w = 1.0
    # Draw one sample from P(G)
    G = np.random.binomial(1,P_G[1])
    # Draw one sample from P(M)
    #M = np.random.binomial(1,P_M[1])
    M = 1
    w *= P_M[M]
    # Draw one sample from P(F|M)
    F = np.random.binomial(1,P_F_M[1,M])
    # Draw one sample from P(P|M)
    P = np.random.binomial(1,P_P_M[1,M])
    Trace[i:] = np.array([G,M,F,P,w])

In [7]:
print(Trace)

[[0.   1.   1.   1.   0.75]
 [1.   1.   0.   0.   0.75]
 [1.   1.   1.   0.   0.75]
 ...
 [0.   1.   1.   0.   0.75]
 [0.   1.   1.   1.   0.75]
 [1.   1.   1.   0.   0.75]]


In [10]:
print(f"P_G = {np.multiply(Trace[:,0],Trace[:,4]).sum()/Trace[:,4].sum()}")
print(f"P_M = {np.multiply(Trace[:,1],Trace[:,4]).sum()/Trace[:,4].sum()}")
print(f"P_F_M = {np.multiply(Trace[:,2],Trace[:,4]).sum()/Trace[:,4].sum()}")
print(f"P_P_M = {np.multiply(Trace[:,3],Trace[:,4]).sum()/Trace[:,4].sum()}")



P_G = 0.4013
P_M = 1.0
P_F_M = 0.601
P_P_M = 0.5571


A second example - this time conditioning on those people who are programmers. 

In [11]:
N = 10000
Trace = np.zeros([N,5])
for i in range(N):
    w = 1.0
    # Draw one sample from P(G)
    #G = np.random.binomial(1,P_G[1])
    G = 0
    w *= P_G[G]
    # Draw one sample from P(M)
    M = np.random.binomial(1,P_M[1])
    # Draw one sample from P(F|M)
    F = np.random.binomial(1,P_F_M[1,M])
    # Draw one sample from P(P|M)
    #P = np.random.binomial(1,P_P_M[1,M])
    P = 1
    w *= P_P_M[P,M]
    Trace[i:] = np.array([G,M,F,P,w])

In [12]:
print(f"P_G = {np.multiply(Trace[:,0],Trace[:,4]).sum()/Trace[:,4].sum()}")
print(f"P_M = {np.multiply(Trace[:,1],Trace[:,4]).sum()/Trace[:,4].sum()}")
print(f"P_F_M = {np.multiply(Trace[:,2],Trace[:,4]).sum()/Trace[:,4].sum()}")
print(f"P_P_M = {np.multiply(Trace[:,3],Trace[:,4]).sum()/Trace[:,4].sum()}")



P_G = 0.0
P_M = 0.7842771130249218
P_F_M = 0.517024235957625
P_P_M = 1.0
